# -*- coding: utf-8 -*-
"""D10PartA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ssQXBpPTnALw0cj7UuIJv31dwBFmC3l9
"""

from collections import defaultdict

# Product Catalog
catalog = {
    'SKU001': {'name': 'Laptop', 'price': 65000, 'category': 'electronics', 'stock': 15, 'rating': 4.5, 'tags': ['computer', 'work']},
    'SKU002': {'name': 'Smartphone', 'price': 25000, 'category': 'electronics', 'stock': 30, 'rating': 4.3, 'tags': ['mobile', 'android']},
    'SKU003': {'name': 'Headphones', 'price': 2000, 'category': 'electronics', 'stock': 0, 'rating': 4.1, 'tags': ['audio', 'music']},
    'SKU004': {'name': 'Smartwatch', 'price': 5000, 'category': 'electronics', 'stock': 12, 'rating': 4.0, 'tags': ['wearable', 'fitness']},

    'SKU005': {'name': 'T-Shirt', 'price': 800, 'category': 'clothing', 'stock': 50, 'rating': 3.9, 'tags': ['casual', 'cotton']},
    'SKU006': {'name': 'Jeans', 'price': 1800, 'category': 'clothing', 'stock': 25, 'rating': 4.2, 'tags': ['denim', 'casual']},
    'SKU007': {'name': 'Jacket', 'price': 3500, 'category': 'clothing', 'stock': 10, 'rating': 4.4, 'tags': ['winter', 'fashion']},
    'SKU008': {'name': 'Sneakers', 'price': 2500, 'category': 'clothing', 'stock': 0, 'rating': 4.1, 'tags': ['shoes', 'sport']},

    'SKU009': {'name': 'Python Programming', 'price': 600, 'category': 'books', 'stock': 20, 'rating': 4.7, 'tags': ['programming', 'python']},
    'SKU010': {'name': 'Data Science Handbook', 'price': 750, 'category': 'books', 'stock': 18, 'rating': 4.6, 'tags': ['data', 'science']},
    'SKU011': {'name': 'Machine Learning Guide', 'price': 900, 'category': 'books', 'stock': 5, 'rating': 4.5, 'tags': ['ai', 'ml']},
    'SKU012': {'name': 'Fiction Novel', 'price': 400, 'category': 'books', 'stock': 0, 'rating': 3.8, 'tags': ['story', 'novel']},

    'SKU013': {'name': 'Chocolate', 'price': 200, 'category': 'food', 'stock': 100, 'rating': 4.4, 'tags': ['sweet', 'snack']},
    'SKU014': {'name': 'Organic Honey', 'price': 450, 'category': 'food', 'stock': 40, 'rating': 4.6, 'tags': ['organic', 'healthy']},
    'SKU015': {'name': 'Green Tea', 'price': 300, 'category': 'food', 'stock': 0, 'rating': 4.3, 'tags': ['tea', 'healthy']}
}


# 1. Search products by tag
def search_by_tag(tag):
    tag_map = defaultdict(list)

    for sku, product in catalog.items():
        for t in product.get('tags', []):
            tag_map[t].append(product)

    return tag_map.get(tag, [])


# 2. Find out of stock products
def out_of_stock():
    return {
        sku: product
        for sku, product in catalog.items()
        if product.get('stock', 0) == 0
    }


# 3. Filter products by price range
def price_range(min_price, max_price):
    return {
        sku: product
        for sku, product in catalog.items()
        if min_price <= product.get('price', 0) <= max_price
    }


# 4. Category summary
def category_summary():
    category_data = defaultdict(list)

    for product in catalog.values():
        category = product.get('category')
        category_data[category].append(product)

    summary = {}

    for category, products in category_data.items():
        count = len(products)
        avg_price = sum(p.get('price', 0) for p in products) / count
        avg_rating = sum(p.get('rating', 0) for p in products) / count

        summary[category] = {
            'count': count,
            'avg_price': round(avg_price, 2),
            'avg_rating': round(avg_rating, 2)
        }

    return summary


# 5. Apply discount to a category
def apply_discount(category, percent):
    return {
        sku: {
            **product,
            'price': product.get('price', 0) * (1 - percent / 100)
        } if product.get('category') == category else product
        for sku, product in catalog.items()
    }


# 6. Merge two catalogs
def merge_catalogs(catalog1, catalog2):
    merged = catalog1 | catalog2
    return merged


# Example Usage
print(category_summary())
print(out_of_stock())
print(price_range(500, 5000))
print(search_by_tag('casual'))

