# -*- coding: utf-8 -*-
"""day10partc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cjhq6RLvIdkd6FSFR3iIC-8vQwZpeSfX

## Part C — Interview Ready

### Q1: Conceptual

**Time Complexity of Dictionary Operations**

- **Lookup (accessing a value by key)** → Average **O(1)**
- **Insertion (adding a new key-value pair)** → Average **O(1)**
- **Deletion (removing a key)** → Average **O(1)**

Python dictionaries are implemented using a **hash table**.  
When a key is inserted, Python computes a **hash value** and stores the key-value pair in the corresponding bucket. Because the hash directly points to the storage location, lookup, insertion, and deletion usually take constant time.

**Why Average O(1)**  
The hash function distributes keys across the table so each key maps to a unique or nearly unique index. This avoids scanning the entire structure.

**Worst Case O(n)**  
Worst-case complexity happens when **many keys produce the same hash value**, creating collisions. When collisions occur, Python must check multiple entries in the same bucket, which can degrade performance to **O(n)**.

**Hash Function for Integers vs Strings**

- **Integers**: The hash of an integer is generally the integer itself, making hashing very fast.
- **Strings**: Python computes the hash based on the characters in the string using a polynomial rolling hash algorithm. Python also randomizes string hashing between program runs to prevent hash collision attacks.

**When to Choose a Dictionary over a List**

Use a dictionary when:
- You need **fast lookups by key**
- You want to **store key-value relationships**
- Order is less important than **quick access**

Use a list when:
- You only need **ordered storage**
- Access is primarily by **index**
- Searching by value is acceptable with **O(n)** complexity.

---
"""

### Q2: Coding


from collections import defaultdict

def group_anagrams(words: list[str]) -> dict[str, list[str]]:
    groups = defaultdict(list)

    for word in words:
        key = ''.join(sorted(word))
        groups[key].append(word)

    return dict(groups)


# Example
print(group_anagrams(['eat', 'tea', 'tan', 'ate', 'nat', 'bat']))

### Q2: Coding

from collections import defaultdict

def group_anagrams(words: list[str]) -> dict[str, list[str]]:
    groups = defaultdict(list)

    for word in words:
        key = ''.join(sorted(word))
        groups[key].append(word)

    return dict(groups)


# Example
print(group_anagrams(['eat', 'tea', 'tan', 'ate', 'nat', 'bat']))

