# -*- coding: utf-8 -*-
"""Log Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jj4VSAOTmi7tzOwaPHrSxX2Aq2h9s9ye
"""

from collections import Counter, defaultdict

logs = [
"2026-03-01 10:00:01 INFO auth User login successful",
"2026-03-01 10:01:15 ERROR database Connection timeout",
"2026-03-01 10:02:20 WARNING api Slow response detected",
"2026-03-01 10:03:10 INFO auth Token generated",
"2026-03-01 10:04:55 ERROR payment Payment processing failed",
"2026-03-01 10:05:30 ERROR database Query execution failed",
"2026-03-01 10:06:12 CRITICAL server System out of memory",
"2026-03-01 10:07:44 INFO api Request processed",
"2026-03-01 10:08:01 ERROR auth Invalid password",
"2026-03-01 10:09:50 WARNING database High latency detected"
]

def parse_log(line):
    parts = line.split(" ", 4)
    return {
        "timestamp": parts[0] + " " + parts[1],
        "level": parts[2],
        "module": parts[3],
        "message": parts[4]
    }

parsed_logs = [parse_log(line) for line in logs]

error_messages = Counter()
module_activity = Counter()
level_distribution = Counter()
errors_by_module = defaultdict(list)

for entry in parsed_logs:
    level = entry.get("level")
    module = entry.get("module")
    message = entry.get("message")

    level_distribution[level] += 1
    module_activity[module] += 1

    if level in ["ERROR", "CRITICAL"]:
        error_messages[message] += 1
        errors_by_module[module].append(message)

total_entries = len(parsed_logs)
error_count = level_distribution.get("ERROR", 0) + level_distribution.get("CRITICAL", 0)

summary = {
    "total_entries": total_entries,
    "error_rate": round((error_count / total_entries) * 100, 2),
    "top_errors": error_messages.most_common(3),
    "busiest_module": module_activity.most_common(1)[0][0]
}

print("Log Level Distribution:", level_distribution)
print("Most Active Modules:", module_activity)
print("Top Error Messages:", error_messages.most_common(3))
print("Errors Grouped by Module:", dict(errors_by_module))
print("Summary:", summary)

